<a href="https://colab.research.google.com/github/swethapatil-168/Python-course/blob/main/Practice_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape 

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [21]:
b= np.array([(1,2,3,4) ,(5,6,7,8)])
print(b)
c=np.array([[1,2],[3,4]], dtype=complex)
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [28]:
print(np.zeros((3,4)),'\n')
print(np.ones((4, 3, 4), dtype=np.int16),'\n')
print(np.empty((2,3)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [31]:
np.arange(10, 30, 5)
# np.arange(0, 2, 0.3)

array([10, 15, 20, 25])

In [38]:
from numpy import pi
np.linspace(0, 2, 9)
x = np.linspace(0, 2*pi, 100)
f = np.tanh(x)
f

array([0.        , 0.06338144, 0.12625569, 0.18813165, 0.24854937,
       0.30709305, 0.36340125, 0.41717396, 0.46817631, 0.51623904,
       0.56125619, 0.60318055, 0.64201738, 0.6778171 , 0.71066753,
       0.74068615, 0.76801266, 0.79280227, 0.81521977, 0.83543448,
       0.85361606, 0.86993125, 0.8845413 , 0.89760013, 0.90925308,
       0.91963611, 0.92887539, 0.93708726, 0.94437835, 0.9508459 ,
       0.95657821, 0.96165517, 0.96614879, 0.97012382, 0.97363834,
       0.9767443 , 0.97948812, 0.98191117, 0.9840503 , 0.98593825,
       0.98760412, 0.98907373, 0.99036995, 0.99151305, 0.99252098,
       0.99340959, 0.99419294, 0.99488341, 0.99549197, 0.99602829,
       0.99650092, 0.99691739, 0.99728436, 0.9976077 , 0.99789258,
       0.99814357, 0.99836469, 0.99855949, 0.9987311 , 0.99888228,
       0.99901545, 0.99913277, 0.99923611, 0.99932714, 0.99940732,
       0.99947796, 0.99954017, 0.99959498, 0.99964325, 0.99968577,
       0.99972322, 0.99975621, 0.99978527, 0.99981087, 0.99983

In [39]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [43]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a -b 
c

array([20, 29, 38, 47])

In [46]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])                       
print(A * B,'\n')    # elementwise product)
print(A @ B,'\n')     # matrix product
print(A.dot(B),'\n')

[[2 0]
 [0 4]] 

[[5 4]
 [3 4]] 

[[5 4]
 [3 4]] 



In [49]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print(a)
b += a
print(b)


[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [53]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B, C) )

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


In [56]:
a = np.arange(10)**3 
a[2]
print(a)
a[2 : 5] 
print(a)
a[ : 6 : 2] = 1000
print(a)

[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[1000    1 1000   27 1000  125  216  343  512  729]
